// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cornershopdb

type Device struct {
	ID    string `json:"id"`
	Agent string `json:"agent"`
}

type Episode struct {
	ID              int64  `json:"id"`
	AnimeSeason     string `json:"anime_season"`
	AnimeTitle      string `json:"anime_title"`
	AudioTerm       string `json:"audio_term"`
	EpisodeNumber   string `json:"episode_number"`
	FileChecksum    string `json:"file_checksum"`
	FileExtension   string `json:"file_extension"`
	FileName        string `json:"file_name"`
	ReleaseGroup    string `json:"release_group"`
	Source          string `json:"source"`
	VideoResolution string `json:"video_resolution"`
	VideoTerm       string `json:"video_term"`
}

type UserSession struct {
	ID            int64  `json:"id"`
	Device        string `json:"device"`
	AnimeTitle    string `json:"anime_title"`
	EpisodeNumber string `json:"episode_number"`
	Playing       bool   `json:"playing"`
	Transcoding   bool   `json:"transcoding"`
	Position      int64  `json:"position"`
}
