// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package cornershopdb

type Episode struct {
	ID              int64  `json:"id"`
	AnimeSeason     string `json:"anime_season"`
	AnimeTitle      string `json:"anime_title"`
	AudioTerm       string `json:"audio_term"`
	EpisodeNumber   string `json:"episode_number"`
	FileChecksum    string `json:"file_checksum"`
	FileExtension   string `json:"file_extension"`
	FileName        string `json:"file_name"`
	ReleaseGroup    string `json:"release_group"`
	Source          string `json:"source"`
	VideoResolution string `json:"video_resolution"`
	VideoTerm       string `json:"video_term"`
}
